version: '3.8'

services:
  algorithmic-trading:
    image: algorithmic-trading-app:latest
    container_name: algorithmic-trading-container
    runtime: nvidia
    stdin_open: true
    tty: true
    volumes:
      # Data and results directories (using Windows paths)
      - ${LOCAL_DATA_PATH:-./data}:/app/data
      - ${LOCAL_RESULTS_PATH:-./EnhancedTrainingResults}:/app/EnhancedTrainingResults
      # Mount the source code files directly
      - ./main.py:/app/main.py
      - ./data_manager.py:/app/data_manager.py
      - ./model_management.py:/app/model_management.py
      - ./feature_engineering.py:/app/feature_engineering.py
      - ./trading_logic.py:/app/trading_logic.py
      - ./memory_utils.py:/app/memory_utils.py
      - ./data_preparation.py:/app/data_preparation.py
      - ./config_unified.py:/app/config_unified.py
      - ./api_security.py:/app/api_security.py
      - ./unified_monitor.py:/app/unified_monitor.py
      - ./memory_tester.py:/app/memory_tester.py
      - ./startup.sh:/app/startup.sh
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY:-}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET:-}
      - CRYPTO_SYSTEM_GPU_MEMORY_LIMIT_PCT=65
      - TF_ENABLE_XLA=1
      - TF_ENABLE_ONEDNN_OPTS=1
      - OPTIMIZE_FOR_RTX_4070=1
      - PYTHONPATH=/app:/app/src
    deploy:
      resources:
        limits:
          cpus: '14'
          memory: 50G
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    shm_size: 8g
    ulimits:
      memlock: -1
      stack: 67108864
    mem_limit: 50g
    memswap_limit: 55g
    entrypoint: ["/bin/bash"]
    command: ["/app/startup.sh"]